# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Martha Weisheimer
tagline:          'A little bit about me'
description:      'A former stagehand shifting into a career in software development" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://www.marthaweisheimer.com/
baseurl:          https://www.marthaweisheimer.com/

author:
  name:           'Martha Weisheimer'
  url:            www.marthaweisheimer.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/marthaweisheimer
